# Generated by Django 5.0 on 2023-12-10 17:24

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userbankaccount',
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
